[theme]
base = "light"
primaryColor = "#00C4A7"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F8FA"
textColor = "#001D3D"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
